export const USER_SIGNIN_API = "USER_SIGNIN_API"; 


export const USLOGIN = "USLOGIN"; 

export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA"; 

export const GET_ALL_PROJECT = "GET_ALL_PROJECT";

export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA';
export const GET_ALL_TYPE_TASK_SAGA = 'GET_ALL_TYPE_TASK_SAGA'

export const GET_ALL_TASK_TYPE = 'GET_ALL_TASK_TYPE';
export const GET_ALL_PRIORITY_LIST_SAGA = 'GET_ALL_PRIORITY_LIST_SAGA';
export const GET_ALL_PRIORITY_DROPDOWN = 'GET_ALL_PRIORITY_DROPDOWN'

export const GET_ALL_STATUS = 'GET_ALL_STATUS';
export const GET_ALL_STATUS_SAGA = 'GET_ALL_STATUS_SAGA';
export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA'
